gameproject/src/Entity/Membre.php
<?php


namespace Entity;


class Membre {
    
    /**
     *
     * @var int 
     */
    private $id_membre;
    
    /**
     *
     * @var string
     */
    private $pseudo;
    
    /**
     *
     * @var string
     */
    private $mdp;
    
    /**
     *
     * @var int
     */
    private $score;
    
    /**
     *
     * @var string
     */
    private $statut_membre;
    
    //Getters:
    
    /**
     * 
     * @return int
     */
    public function getId_membre() {
        return $this->id_membre;
    }
    
    /**
     * 
     * @return string
     */
    public function getPseudo() {
        return $this->pseudo;
    }
    
    /**
     * 
     * @return string
     */
    public function getMdp() {
        return $this->mdp;
    }
    
    /**
     * 
     * @return int
     */
    public function getScore() {
        return $this->score;
    }
    
    /**
     * 
     * @return string
     */
    public function getStatut_membre() {
        return $this->statut_membre;
    }

    //Setters:
    
    /**
     * 
     * @param type $id_membre
     * @return $this
     */
    public function setId_membre($id_membre) {
        $this->id_membre = $id_membre;
        return $this;
    }
    
    /**
     * 
     * @param type $pseudo
     * @return $this
     */
    public function setPseudo($pseudo) {
        $this->pseudo = $pseudo;
        return $this;
    }
    
    /**
     * 
     * @param type $mdp
     * @return $this
     */
    public function setMdp($mdp) {
        $this->mdp = $mdp;
        return $this;
    }

    /**
     * 
     * @param type $score
     * @return $this
     */
    public function setScore($score) {
        $this->score = $score;
        return $this;
    }
    
    /**
     * 
     * @param type $statut_membre
     * @return $this
     */
    public function setStatut_membre($statut_membre) {
        $this->statut_membre = $statut_membre;
        return $this;
    }
    
    public function isAdmin(){
        if($this->statut_membre == 1) return true;
        else return false;
    }


           
}

gameproject/templates/credits.html.twig
{% extends "layout.html.twig" %}

{% block title "Politismos Quiz : Crédits" %}
{% block stylesheets %} 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{{ asset('assets/images/earth.png') }}" />
    <link href="{{ asset('assets/css/credits.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    
    <div class="container">
        
        <div class="row">
    
            <h1>Jeu développé par :</h1>
            <ul class="namesList">
                <li id="sonia"><h2>Sonia Daguet</h2></li>
                <li id="david"><h2>David Spanjaard</h2></li>
            </ul>
    
        </div>
        
    </div>
    
{% endblock %}

gameproject/templates/finDePartie.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>{% block title '- Fin de partie' %}</title>
            
        {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('assets/css/game.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('assets/css/rules.css') }}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/css/endOfGame.css') }}" rel="stylesheet" type="text/css"/>
        <link rel="icon" type="image/png" href="{{ asset('assets/images/earth.png') }}" />
        {% endblock %}

    </head>
    <body>
        
        <nav class="navbar navbar-default">
            <div class="container" id="navbar-container">
                <ul class="nav navbar-nav navbar-right">
                    <li class="bottom">
                        <a href="{{ path('homepage') }}" class="bold">Accueil</a>
                    </li>
                    <li>
                        <a class="font" href="{{ path('scores') }}">Tableau des scores</a>
                    </li>
                </ul>  
            </div>
        </nav> 
            
        <div class="container">
            <div class="row">
                <h1 class="col-md-12 col-md-offset-0" id="rappelTitre">Politismos Quiz</h1>
            </div>
            
            <div class="row" >
             {# image affichée à la fin du jeu en fonction du score du joueur #}    
                {% if membre_manager.score < 600 %}
                    <img id="logo" src="{{ asset('assets/images/restricted.png') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score >= 600 and membre_manager.score < 1200 %}
                    <img id="logo" src="{{ asset('assets/images/participer.jpg') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score >= 1200 and membre_manager.score < 2000 %}
                    <img id="logo" src="{{ asset('assets/images/deguise.jpg') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score >= 2000 and membre_manager.score < 2800 %}
                    <img id="logo" src="{{ asset('assets/images/carte.jpg') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score >= 2800 and membre_manager.score < 4000%}
                    <img id="logo" src="{{ asset('assets/images/station.jpg') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score >= 4000 and membre_manager.score < 6300 %}
                    <img id="logo" src="{{ asset('assets/images/seconde.jpg') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score >= 6300 and membre_manager.score < 7300 %}
                    <img id="logo" src="{{ asset('assets/images/terre.jpg') }}" alt="logo">
                {% endif%}
                
                {% if membre_manager.score == 7300 %}
                    <img id="logo" src="{{ asset('assets/images/best.jpg') }}" alt="logo">
                {% endif%}
            </div>
            
            <div class="row">
                <h3 id="score" class="col-md-12 col-md-offset-0">Score : {{ membre_manager.score }}</h3>
            </div>
            
            <div class="row">
                <p class="col-md-12 col-md-offset-0" id="paragraph">
                {# message affiché à la fin du jeu en fonction du score du joueur #}
                  {% if membre_manager.score < 600 %}
                    {# moins de 600 points #}
                    Nous pensons que vous n'êtes pas prêt(e) pour le monde des humains.
                    Entraînez-vous et retentez l'expérience dans quelques années !
                  {% endif%}
                
                  {% if membre_manager.score >= 600 and membre_manager.score < 1200 %}
                    {# entre 600 et moins de 1200 points #}
                    Pas mal mais pas suffisant!
                    L'essentiel c'est que vous ayez participé. 
                  {% endif%}
                
                  {% if membre_manager.score >= 1200 and membre_manager.score < 2000 %}
                    {# entre 1200 et moins de 2000 points #}
                   Nous apprécions vos efforts mais ce ne sera pas suffisant pour passer inaperçu(e) parmi les humains.
                  {% endif%}
                  
                  {% if membre_manager.score >= 2000 and membre_manager.score < 2800 %}
                    {# entre 2000 et moins de 2800 points #}
                     Vous n'irez pas sur Terre pour cette fois mais nous vous offrons une carte de la planète Terre!
                  {% endif%}
                  
                  {% if membre_manager.score >= 2800 and membre_manager.score < 4000%}
                    {# entre 2800 et moins de 4000 points #} 
                     Nous croyons en vous!
                     Pour votre peine, nous vous offrons une visite gratuite de notre station spatiale Politismos3!
                  {% endif%}
                  
                  {% if membre_manager.score >= 4000 and membre_manager.score < 6300 %}
                    {# entre 4000 et moins de 6300 points #}
                    Vous y étiez presque! 
                    Nous vous offrons une seconde chance au quiz pour remporter le voyage et rencontrer les Humains!
                  {% endif%}
                  
                  {% if membre_manager.score >= 6300 and membre_manager.score < 7300 %}
                    {# entre 6300 points et moins de 7300 points #}
                    Bon travail! Vous avez réussi!
                    Prêt(e) pour l'aventure de votre vie avec Politismos.Inc? 
                  {% endif%}
                  
                  {% if membre_manager.score == 7300 %}
                    {#7300 points(score maximum avec combos)#}
                    Waouh! Nous sommes impressionnés! 
                    Vous êtes de loin notre meilleur(e) candidat(e)!
                    Vous seriez sans doute capable de conduire vous-même la navette! 
                  {% endif%} 
                </p>
            </div>
        </div>
                
        {% block javascript %}
        {#récupérerer les liens sur bootstrap#}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

gameproject/templates/game.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title 'Politismos Quiz' %}</title>
        {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('assets/css/game.css') }}" rel="stylesheet" type="text/css" />
        <link rel="icon" type="image/png" href="{{ asset('assets/images/earth.png') }}" />
        {% endblock %}

    </head>
    <body>
        
        <div class="homeButton">
            <a href="{{ path('homepage') }}"><img id="home" src="{{ asset('assets/images/home.png') }}" alt="home"></a>
        </div>
        
        <div class="titleContainer">
            <h1>Politismos Quiz</h1>
            <h2 id="score">Score :  0</h2>
        </div>
        
        <div class="jokerRow">
                
            <button id="joker1" type="button" class="jokerButton jokerButton-primary margin-top-5" data-toggle="tooltip" data-placement="top" title="Changer de question">Switch</button>
                
            <button id="joker2" type="button" class="jokerButton jokerButton-primary margin-top-5" data-toggle="tooltip" data-placement="top" title="Enlever deux mauvaises réponses">50/50</button>

        </div>
            
        <h3 id="questionNumber" class="margin-top-5">Question n°</h3>
            
        <p id="questionText">Texte de la question</p>

        <div class="buttonRow">
            <button id="reponseA" class="reponseButton reponseButton-primary margin-top-5">Réponse A</button>
            <button id="reponseB" class="reponseButton reponseButton-primary margin-top-5">Réponse B</button>
        </div>
            
        <div class="buttonRow">
            <button id="reponseC" class="reponseButton reponseButton-primary margin-top-5">Réponse C</button>
            <button id="reponseD" class="reponseButton reponseButton-primary margin-top-5">Réponse D</button>
        </div>
            
        <button id="valider" class="validateButton validateButton-primary margin-top-5 margin-bottom-5">Valider</button>
        
        <div id="combo">
            <p class="yellow">Combo x3</p>
        </div>
        {% block javascript %}
       {#récupérerer les liens sur bootstrap#}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.4/howler.core.min.js"></script>
            <script>
                var path = '{{ path('randomQuestion') }}';
                var path2 = '{{ path("best-score") }}';
                var path3 = '{{ path('fin_de_partie') }}';
            </script>
            <script src="../assets/js/sound.js"></script>
            <script src="../assets/js/questionRequest.js"></script>
            <script src="../assets/js/game.js"></script>
            <script src="../assets/js/affichage-donnees.js"></script>
            <script src="../assets/js/score.js"></script>
            <script src="../assets/js/joker.js"></script>
            <script src="../assets/js/verificationReponses.js"></script>
            <script src="../assets/js/PostBestScore.js"></script>

        {% endblock %}
    </body>
</html>

gameproject/templates/index.html.twig
{% extends "layout.html.twig" %}
{% block title 'Politismos Quiz : Accueil'%}
{% block stylesheets %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('assets/css/accueil.css') }}" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="{{ asset('assets/images/earth.png') }}" />
{% endblock %}   

{% block content %}
    <div class="container">
        <div class="row">
            {# On affiche sur la vue un message, si un joueur n'est pas connecté#}
            {% if not membre_manager.membre %}
                <p class='alert alert-danger col-md-2 col-md-offset-4'>Attention, si vous n'êtes pas connecté votre score ne sera pas sauvegardé !</p>
            {% endif %}
        </div>
        
        <div class="row">
            <h1 class="col-md-2 col-md-offset-4 col-xs-6 col-xs-offset-3" id="mainTitle">Politismos Quiz</h1>
        </div>
    
        <div class="row">
            <a href="{{ path('game') }}" class="btn btn-primary col-md-2 col-md-offset-4 margin-top-5 col-xs-6 col-xs-offset-3" role="button">Jouer</a>
        </div>
        
        <div class="row">
            <a href="{{ path('regles') }}" class="btn btn-primary col-md-2 col-md-offset-4 margin-top-5 col-xs-6 col-xs-offset-3" role="button">Règles du jeu</a>
        </div>
        
        <div class="row">
            <a href="{{ path('scores') }}" class="btn btn-primary col-md-2 col-md-offset-4 margin-top-5 col-xs-6 col-xs-offset-3 {% if not membre_manager.membre %}margin-button{% endif%}" role="button">Scores</a>
        </div>
        
       
        {% if membre_manager.membre %}    
        <div class="row" >
            <a href="{{ path('soumission') }}" id="last-button" class="btn btn-primary col-md-2 col-md-offset-4 margin-top-5 col-xs-6 col-xs-offset-3 margin-button" role="button">Proposer une question</a>
        </div>
        {% endif %}
        
        <div class="row">
            <a href="{{ path('credits') }}" class="btn btn-primary col-md-2 col-md-offset-4 margin-top-5 col-xs-6 col-xs-offset-3" role="button">Crédits</a>
        </div>
        
        {% block javascript %}
            {{ parent() }}
            <script src="https://cdnjs.cloudflare.com/ajax/libs/howler/2.0.4/howler.core.min.js"></script>
            <script src="../assets/js/accueil.js"></script>
        {% endblock %}
    </div>
        
{% endblock %}

gameproject/templates/layout.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title 'Politismos Quiz' %}</title>
        {% block stylesheets %}
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{{ asset('assets/css/main.css') }}" rel="stylesheet" type="text/css" />
        <link href="{{ asset('assets/css/rules.css') }}" rel="stylesheet" type="text/css" />
        <link rel="icon" type="image/png" href="{{ asset('assets/images/earth.png') }}" />
        {% endblock %}

    </head>
    <body>
        {% if membre_manager.admin %}
            <nav class="navbar navbar-inverse" id="navbar-admin"> 
                <div class="container">
                    
                        <ul class="nav navbar-nav">
                            <li>
                                <a class="navbar-brand">Menu admin</a>
                            </li>
                            <li>
                                <a href='{{ path('admin_validation')}}'>Gestion des questions</a>
                            </li>
                        </ul>
                </div>
            </nav>
        {% endif %}               
        <nav class="navbar navbar-default">
                <div class="container" id="navbar-container">
                    
                        <ul class="nav navbar-nav navbar-right">
                            <li class="bottom"><a href="{{ path('homepage') }}" class="bold">Accueil</a></li>
                            
                           {% if membre_manager.membre %}
                               
                            <li id="messageUser">
                                Bienvenue {{ membre_manager.membrePseudo }}
                            </li> 
                             
                            <li class="top">
                                <a href="{{ path('deconnexion') }}">Deconnexion</a>
                            </li>
                               
                            {% else %}
                                
                            <li class="top">
                                <a href="{{ path('inscription') }}">Créer un compte</a>
                            </li>
                            
                            <li class="top">
                                <a href="{{ path('connexion') }}">Connexion</a>
                            </li>
                           
                            {% endif %}
                            

                        </ul>
                </div>
        </nav>
        <div class="container">
        {%for type, flashes in app.session.flashbag.all%}
            {# permet d'accéder dans tous ce qui est dans app et d'afficher des messages flash #}
                {% for flash in flashes %}
                    {% if type == 'error' %}
                        {% set type = 'danger' %}
                    {% endif %}
                    <div class="alert alert-{{ type }}">
                        {# pour ne pas echapper les balises html c à dire que les chevrons ne soient pas visibles jiq#}
                        {{ flash|raw }}
                    </div>
                {% endfor %}
        {% endfor%}
        </div>
        {% block content %}
         
        {% endblock %}
        {% block javascript %}
       {#récupérerer les liens sur bootstrap#}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% endblock %}
    </body>
</html>

gameproject/templates/regles.html.twig
{% extends "layout.html.twig" %}

{% block title "Politismos Quiz : Régles du jeu"%}

{% block content %}
    <div class="container">
        <div class="row">
             <h1 class='col-md-0 col-md-offset-4 col-sm-offset-4 col-xs-6 col-xs-offset-1' id="welcome"> Welcome to Dagovarana</h1>
        </div>
        
        <div class="row" >

            <img id ="logo" src="{{ asset('assets/images/earth.png') }}" alt="logo">
            
            <ul class="list-group list-group-flush" id='cadre'>
                  
                <li class="story">
                    Félicitations habitant(e) de Dagovarana.
                </li>
                
                <li class="story">
                    Vous avez été sélectionné(e) pour participer au voyage intersidéral, qui vous permettra de passer un an sur la planète Terre. 
                    Mais avant cela, une dernière étape il vous faudra passer..
                    Nous recherchons, en effet, des candidat(e)s motivé(e)s et ayant un minimum de connaissances sur les Humains. 
                </li>
                
                <li class="story">
                    Ils sont très sensibles à ce qu'ils nomment communément la culture G. 
                    Nous allons donc vous faire passer un test à ce sujet, sous forme de quiz.  
                    Mais ne vous inquiétez pas nous sommes convaincu que vous y arriverez. 
                </li>
                    
                <li class="story">
                    Surtout pensez à bien lire les régles avant de commencer.
                </li>
                
                <li class="story">
                    POLITISMOS.INC<br>
                    "La compagnie spatiale proche de vous".
                </li>
            </ul>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-block">

                    <h2 class="card-title text-center" id="gameRules">Règles du jeu</h2>

                    <ul id="rules" class="list-group list-group-flush">
                
                        <li class="rule">
                            Sélectionnez une seule réponse par question posée et validez-la ensuite à l'aide du bouton valider.
                        </li>
                    
                        <li class="rule">
                            Au bout de trois mauvaises réponses, la partie se termine.
                        </li>
                    
                        <li class="rule">
                            Pour vous aidez, vous avez à votre disposition deux jokers: le switch et le cinquante-cinquante.
                        </li>
                        
                        <li class="rule">
                            Le joker switch permet de changer de question au cours de la partie.
                        </li> 
                        
                        <li class="rule">
                            Le joker cinquante-cinquante permet de retirer deux mauvaises réponses à la question et vous laisse donc un choix à deux réponses au lieu de quatre.
                        </li>  
                        
                        <li class="rule">
                            Attention chaque joker ne peut être utilisé qu'une seule fois au cours de la partie.
                            Ils peuvent cependant être utilisés conjointement durant la même manche.  
                        </li>
                        
                        <li class="rule">
                            Si vous réalisez un combo de trois bonnes réponses à la suite, votre score sera multiplié.
                            N'oubliez pas que votre réussite au quiz dépendra de votre score.
                        </li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

   

                       

                        

                        

gameproject/templates/score.html.twig
{% extends "layout.html.twig" %}

{% block title "Politismos Quiz : Scores" %}
    
{% block content %}
<div class="container">
    <h1>Meilleurs scores</h1>
    
    <table class="table">
        <tr>
            <th>Pseudo</th>
            <th>Score</th>
            {% if membre_manager.admin %}
            <th>Action</th>
            {% endif %}
        </tr>
        
        {% for membre in membres %}
        <tr>
            <td>{{ membre.pseudo }}</td>
            <td>{{ membre.score }}</td>
            {% if membre_manager.admin %}
            <td>
                <a href="{{ path('admin_reset_score',{id:membre.id_membre}) }}">
                <img id="option3" src="{{ asset('assets/images/remove.png') }}" alt="remettre à zéro">
                </a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
</div>
    
{% endblock %}

gameproject/templates/soumissionQuestion.html.twig
{% extends "layout.html.twig" %}

{% block title "Politismos Quiz : Soumission de question" %}

{% block content %}

<div class="container">
    <div class="row">
        <h1 class="col-md2 col-md-offset-4">Proposer votre question</h1>
    </div>
    <form method="post">

        <div class="form-group">
            <label for="question">Entrer un texte de question : </label>
            <textarea class="form-control" id="question" name="question" placeholder="Votre question">{{ question.question }}</textarea>
        </div>

        <div class="form-group">
            <label for="reponseA">Entrer votre réponse A : </label>
            <input type="text" class="form-control" id="reponseA" name ="reponseA" value="{{ question.reponse_a }}" placeholder="Votre réponse A">
        </div>

        <div class="form-group">
            <label for="reponseB">Entrer votre réponse B : </label>
            <input type="text" class="form-control" id="reponseB" name ="reponseB" value="{{ question.reponse_b }}" placeholder="Votre réponse B">
        </div>

        <div class="form-group">
            <label for="reponseC">Entrer votre réponse C : </label>
            <input type="text" class="form-control" id="reponseC" name ="reponseC" value="{{ question.reponse_c }}" placeholder="Votre réponse C">
        </div>

        <div class="form-group">
            <label for="reponseD">Entrer votre réponse D : </label>
            <input type="text" class="form-control" id="reponseD" name ="reponseD" value="{{ question.reponse_d }}" placeholder="Votre réponse D">
        </div>

        <div class="form-group">
            <label for="reponse">Quelle est la bonne réponse ?</label>
            <select id="reponse" name="reponse">
                <option value="a"
                    {% if question.bonne_reponse == "a" %}selected{% endif %}>
                    Réponse A
                </option>
                
                <option value="b"
                    {% if question.bonne_reponse == "b" %}selected{% endif %}>
                    Réponse B
                </option>
                
                <option value="c"
                    {% if question.bonne_reponse == "c" %}selected{% endif %}>
                    Réponse C
                </option>
                
                <option value="d"
                    {% if question.bonne_reponse == "d" %}selected{% endif %}>
                    Réponse D
                </option>
            </select>
        </div>

        <div class="form-group">
            <label for="difficulte">Quel est le niveau de difficulté de votre question ?</label>
            <select id="difficulte" name="difficulte">
                <option value="1" {% if question.niveau == "1" %}selected{% endif %}>1</option>
                <option value="2" {% if question.niveau == "2" %}selected{% endif %}>2</option>
                <option value="3" {% if question.niveau == "3" %}selected{% endif %}>3</option>
                <option value="4" {% if question.niveau == "4" %}selected{% endif %}>4</option>
                <option value="5" {% if question.niveau == "5" %}selected{% endif %}>5</option>
                <option value="6" {% if question.niveau == "6" %}selected{% endif %}>6</option>
                <option value="7" {% if question.niveau == "7" %}selected{% endif %}>7</option>
                <option value="8" {% if question.niveau == "8" %}selected{% endif %}>8</option>
                <option value="9" {% if question.niveau == "9" %}selected{% endif %}>9</option>
                <option value="10" {% if question.niveau == "10" %}selected{% endif %}>10</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary margin-button">Soumettre la question</button>
    </form>
    
</div>
    
{% endblock %}